# Generated by Django 4.1.5 on 2023-01-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('RB', 'rainbow'), ('CB', 'centered_rainbow'), ('BR', 'breathing'), ('SO', 'solid_color'), ('PS', 'pulsing_stripes')], max_length=20)),
                ('active', models.BooleanField()),
                ('led_settings', models.JSONField()),
            ],
        ),
    ]
