# Generated by Django 4.1.5 on 2023-01-16 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='speed',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
