# Generated by Django 4.1.5 on 2023-01-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leds', '0003_alter_preset_led_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='preset_name',
            field=models.CharField(default='New Preset', max_length=30),
        ),
    ]
