# Generated by Django 4.1.5 on 2023-01-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leds', '0005_alter_preset_led_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preset',
            name='mode',
            field=models.CharField(choices=[('RB', 'rainbow'), ('CB', 'centered_rainbow'), ('BR', 'breathing'), ('SO', 'solid_color'), ('PS', 'pulsing_stripes')], default='SO', max_length=20),
        ),
    ]
