# Generated by Django 4.1.5 on 2023-01-18 23:14

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leds', '0006_alter_preset_active_alter_preset_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preset',
            name='led_settings',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='speed',
        ),
        migrations.AddField(
            model_name='preset',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='preset',
            name='mode',
            field=models.CharField(choices=[('RB', 'rainbow'), ('SO', 'solid_color'), ('PS', 'pulsing_stripes')], default='SO', max_length=20),
        ),
    ]
